name: CI

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: box
    - uses: actions/checkout@v4
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v3
    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit
    - name: Build PHAR
      run: box compile
    - name: Ensure the PHAR works
      run: bin/converter.phar --ansi --version
    - name: Store binary
      uses: actions/upload-artifact@v4
      with:
        name: converter.phar
        path: bin/converter.phar

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: converter.phar
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: converter.phar
