name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: box
    - uses: actions/checkout@v4
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v3
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
    - name: Build phar
      run: box compile
    - name: Ensure the PHAR works
      run: bin/converter.phar --ansi --version

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Upload release assets
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/converter.phar
          tag: ${{ github.ref }}
